import { readdir, readFile } from "node:fs/promises";
import { join, relative } from "node:path";

const NVST_SKILLS_ROOT = join(import.meta.dir, "..", "..", "nvst-skills");
const OUTPUT_FILE = join(import.meta.dir, "..", "nvst-skills-manifest.ts");

async function walkFiles(directoryPath: string): Promise<string[]> {
  const entries = await readdir(directoryPath, { withFileTypes: true });
  const filePaths: string[] = [];

  for (const entry of entries) {
    const entryPath = join(directoryPath, entry.name);
    if (entry.isDirectory()) {
      filePaths.push(...(await walkFiles(entryPath)));
      continue;
    }
    if (entry.isFile()) {
      filePaths.push(entryPath);
    }
  }

  return filePaths;
}

const files = await walkFiles(NVST_SKILLS_ROOT);
const relativeFiles = files.map((f) => relative(NVST_SKILLS_ROOT, f)).sort();

const entryLines: string[] = [];
for (const rel of relativeFiles) {
  const absPath = join(NVST_SKILLS_ROOT, rel);
  const content = await readFile(absPath, "utf8");
  entryLines.push(`  { relativePath: ${JSON.stringify(rel)}, content: ${JSON.stringify(content)} },`);
}

const entries = entryLines.join("\n");

const fileContent = `// AUTO-GENERATED by src/scripts/generate-nvst-skills-manifest.ts — do not edit manually.
// Re-run \`bun run src/scripts/generate-nvst-skills-manifest.ts\` after adding/removing nvst-skills files.
export const NVST_SKILLS_FILES: Array<{ relativePath: string; content: string }> = [
${entries}
];
`;

await Bun.write(OUTPUT_FILE, fileContent);
console.log(`Generated nvst-skills-manifest.ts with ${files.length} entries.`);
