import { readdir, readFile } from "node:fs/promises";
import { join, relative } from "node:path";

const SCAFFOLD_ROOT = join(import.meta.dir, "..", "..", "scaffold");
const OUTPUT_FILE = join(import.meta.dir, "..", "scaffold-manifest.ts");

async function walkFiles(directoryPath: string): Promise<string[]> {
  const entries = await readdir(directoryPath, { withFileTypes: true });
  const filePaths: string[] = [];

  for (const entry of entries) {
    const entryPath = join(directoryPath, entry.name);
    if (entry.isDirectory()) {
      filePaths.push(...(await walkFiles(entryPath)));
      continue;
    }
    if (entry.isFile()) {
      filePaths.push(entryPath);
    }
  }

  return filePaths;
}

const files = await walkFiles(SCAFFOLD_ROOT);
const relativeFiles = files.map((f) => relative(SCAFFOLD_ROOT, f)).sort();

const entryLines: string[] = [];
for (const rel of relativeFiles) {
  const absPath = join(SCAFFOLD_ROOT, rel);
  const content = await readFile(absPath, "utf8");
  entryLines.push(`  { relativePath: ${JSON.stringify(rel)}, content: ${JSON.stringify(content)} },`);
}

const entries = entryLines.join("\n");

const fileContent = `// AUTO-GENERATED by src/scripts/generate-scaffold-manifest.ts — do not edit manually.
// Re-run \`bun run src/scripts/generate-scaffold-manifest.ts\` after adding/removing scaffold files.
export const SCAFFOLD_FILES: Array<{ relativePath: string; content: string }> = [
${entries}
];
`;

await Bun.write(OUTPUT_FILE, fileContent);
console.log(`Generated scaffold-manifest.ts with ${files.length} entries.`);
