#!/usr/bin/env bun

import { join } from "node:path";
import { parseAgentArg } from "./agent";
import { runStartIteration } from "./commands/start-iteration";
import { runAuditPrototype } from "./commands/audit-prototype";
import { GuardrailAbortError } from "./guardrail";
import { runApprovePrototype } from "./commands/approve-prototype";
import { runApproveRequirement } from "./commands/approve-requirement";
import { runCreatePrototype } from "./commands/create-prototype";
import { runDefineRequirement } from "./commands/define-requirement";
import { runDestroy } from "./commands/destroy";
import { runInit } from "./commands/init";
import { runRefactorPrototype } from "./commands/refactor-prototype";
import { runRefineRequirement } from "./commands/refine-requirement";
import { runWriteJson } from "./commands/write-json";

function extractFlagValue(args: string[], flag: string): { value: string | null; remainingArgs: string[] } {
  const idx = args.indexOf(flag);
  if (idx === -1) {
    return { value: null, remainingArgs: args };
  }

  if (idx + 1 >= args.length) {
    throw new Error(`Missing value for ${flag}.`);
  }

  const value = args[idx + 1];
  return {
    value,
    remainingArgs: [...args.slice(0, idx), ...args.slice(idx + 2)],
  };
}

function parseOptionalIntegerFlag(
  args: string[],
  flag: "--iterations" | "--retry-on-fail",
  min: number,
): { value: number | undefined; remainingArgs: string[] } {
  const { value, remainingArgs } = extractFlagValue(args, flag);
  if (value === null) {
    return { value: undefined, remainingArgs };
  }

  const parsed = Number(value);
  if (!Number.isInteger(parsed) || parsed < min) {
    throw new Error(
      `Invalid ${flag} value '${value}'. Expected an integer >= ${min}.`,
    );
  }

  return { value: parsed, remainingArgs };
}

function parseForce(args: string[]): { force: boolean; remainingArgs: string[] } {
  const force = args.includes("--force");
  return {
    force,
    remainingArgs: args.filter((arg) => arg !== "--force"),
  };
}

function printUsage() {
  console.log(`Usage: nvst <command> [options]

Primary workflow:
  start iteration    Start a new iteration, archiving flow files
  define requirement --agent <provider> [--force]
                     Create requirement document via agent
  refine requirement --agent <provider> [--challenge] [--force]
                     Refine requirement document via agent
  approve requirement [--force]
                     Mark requirement definition as approved
  create prototype --agent <provider> [--iterations <N>] [--retry-on-fail <N>] [--stop-on-critical] [--force]
                     Initialize prototype build for current iteration
  audit prototype --agent <provider> [--force]
                     Execute approved prototype audit tests via agent
  refactor prototype --agent <provider> [--force]
                     Execute approved prototype refactor items via agent
  approve prototype [--force]
                     Stage and commit all pending changes for current iteration

Utilities:
  init               Initialize toolkit files in the current directory
  destroy [--clean]  Remove files generated by nvst
  write-json --schema <name> --out <path> [--data '<json>']
                     Write a schema-validated JSON file (payload via --data or stdin)

Options:
  --agent            Agent provider (claude, codex, gemini, cursor) for agent-backed commands
  --iterations       Maximum prototype passes (integer >= 1)
  --retry-on-fail    Retry attempts per failed story (integer >= 0)
  --stop-on-critical Stop execution after critical failures
  --force            Bypass flow guardrail confirmation
  --challenge        Run requirement refine in challenger mode
  --clean            When used with destroy, also removes .agents/flow/archived
  -h, --help         Show this help message
  -v, --version      Print version and exit`);
}

async function printVersion(): Promise<void> {
  const pkgPath = join(import.meta.dir, "..", "package.json");
  try {
    const pkg = (await Bun.file(pkgPath).json()) as { version?: string };
    console.log(pkg?.version ?? "unknown");
  } catch {
    console.log("unknown");
  }
}

async function main() {
  const [, , command, ...args] = process.argv;

  if (command === "-v" || command === "--version") {
    await printVersion();
    return;
  }

  if (!command || command === "-h" || command === "--help" || command === "help") {
    printUsage();
    return;
  }

  if (command === "init") {
    if (args.length > 0) {
      console.error(`Unknown option(s) for init: ${args.join(" ")}`);
      printUsage();
      process.exitCode = 1;
      return;
    }
    await runInit();
    return;
  }

  if (command === "destroy") {
    const clean = args.includes("--clean");
    const unknownArgs = args.filter((arg) => arg !== "--clean");
    if (unknownArgs.length > 0) {
      console.error(`Unknown option(s) for destroy: ${unknownArgs.join(" ")}`);
      printUsage();
      process.exitCode = 1;
      return;
    }
    await runDestroy({ clean });
    return;
  }

  if (command === "start") {
    if (args.length === 0 || args[0] !== "iteration") {
      console.error("Usage for start: nvst start iteration");
      printUsage();
      process.exitCode = 1;
      return;
    }
    const unknownArgs = args.slice(1);
    if (unknownArgs.length > 0) {
      console.error(`Unknown option(s) for start iteration: ${unknownArgs.join(" ")}`);
      printUsage();
      process.exitCode = 1;
      return;
    }
    await runStartIteration();
    return;
  }

  if (command === "define") {
    if (args.length === 0) {
      console.error("Usage for define: nvst define requirement --agent <provider>");
      printUsage();
      process.exitCode = 1;
      return;
    }

    const subcommand = args[0];
    if (subcommand === "requirement") {
      try {
        const { provider, remainingArgs: postAgentArgs } = parseAgentArg(args.slice(1));
        const { force, remainingArgs: postForceArgs } = parseForce(postAgentArgs);
        if (postForceArgs.length > 0) {
          console.error(`Unknown option(s) for define requirement: ${postForceArgs.join(" ")}`);
          printUsage();
          process.exitCode = 1;
          return;
        }

        await runDefineRequirement({ provider, force });
        return;
      } catch (error) {
        console.error(error instanceof Error ? error.message : String(error));
        printUsage();
        process.exitCode = 1;
        return;
      }
    }

    console.error(`Unknown define subcommand: ${subcommand}`);
    printUsage();
    process.exitCode = 1;
    return;
  }

  if (command === "refine") {
    if (args.length === 0) {
      console.error("Usage for refine: nvst refine requirement --agent <provider> [--challenge]");
      printUsage();
      process.exitCode = 1;
      return;
    }

    const subcommand = args[0];
    if (subcommand === "requirement") {
      try {
        const { provider, remainingArgs: postAgentArgs } = parseAgentArg(args.slice(1));
        const { force, remainingArgs: postForceArgs } = parseForce(postAgentArgs);
        const challenge = postForceArgs.includes("--challenge");
        const unknownArgs = postForceArgs.filter((arg) => arg !== "--challenge");

        if (unknownArgs.length > 0) {
          console.error(`Unknown option(s) for refine requirement: ${unknownArgs.join(" ")}`);
          printUsage();
          process.exitCode = 1;
          return;
        }

        await runRefineRequirement({ provider, challenge, force });
        return;
      } catch (error) {
        console.error(error instanceof Error ? error.message : String(error));
        printUsage();
        process.exitCode = 1;
        return;
      }
    }

    console.error(`Unknown refine subcommand: ${subcommand}`);
    printUsage();
    process.exitCode = 1;
    return;
  }

  if (command === "create") {
    if (args.length === 0) {
      console.error(
        "Usage for create: nvst create prototype --agent <provider> [--iterations <N>] [--retry-on-fail <N>] [--stop-on-critical] [--force]",
      );
      printUsage();
      process.exitCode = 1;
      return;
    }

    const subcommand = args[0];
    if (subcommand === "prototype") {
      try {
        const { provider, remainingArgs: postAgentArgs } = parseAgentArg(args.slice(1));

        const {
          value: iterations,
          remainingArgs: postIterationsArgs,
        } = parseOptionalIntegerFlag(postAgentArgs, "--iterations", 1);
        const {
          value: retryOnFail,
          remainingArgs: postRetryArgs,
        } = parseOptionalIntegerFlag(postIterationsArgs, "--retry-on-fail", 0);

        const { force, remainingArgs: postForceArgs } = parseForce(postRetryArgs);
        const stopOnCritical = postForceArgs.includes("--stop-on-critical");
        const unknownArgs = postForceArgs.filter((arg) => arg !== "--stop-on-critical");
        if (unknownArgs.length > 0) {
          console.error(`Unknown option(s) for create prototype: ${unknownArgs.join(" ")}`);
          printUsage();
          process.exitCode = 1;
          return;
        }

        await runCreatePrototype({ provider, iterations, retryOnFail, stopOnCritical, force });
        return;
      } catch (error) {
        console.error(error instanceof Error ? error.message : String(error));
        printUsage();
        process.exitCode = 1;
        return;
      }
    }

    console.error(`Unknown create subcommand: ${subcommand}`);
    printUsage();
    process.exitCode = 1;
    return;
  }

  if (command === "audit") {
    if (args.length === 0) {
      console.error("Usage for audit: nvst audit prototype --agent <provider> [--force]");
      printUsage();
      process.exitCode = 1;
      return;
    }

    const subcommand = args[0];
    if (subcommand === "prototype") {
      try {
        const { provider, remainingArgs: postAgentArgs } = parseAgentArg(args.slice(1));
        const { force, remainingArgs: postForceArgs } = parseForce(postAgentArgs);
        if (postForceArgs.length > 0) {
          console.error(`Unknown option(s) for audit prototype: ${postForceArgs.join(" ")}`);
          printUsage();
          process.exitCode = 1;
          return;
        }

        await runAuditPrototype({ provider, force });
        return;
      } catch (error) {
        console.error(error instanceof Error ? error.message : String(error));
        printUsage();
        process.exitCode = 1;
        return;
      }
    }

    console.error(`Unknown audit subcommand: ${subcommand}`);
    printUsage();
    process.exitCode = 1;
    return;
  }

  if (command === "refactor") {
    if (args.length === 0) {
      console.error("Usage for refactor: nvst refactor prototype --agent <provider> [--force]");
      printUsage();
      process.exitCode = 1;
      return;
    }

    const subcommand = args[0];
    if (subcommand === "prototype") {
      try {
        const { provider, remainingArgs: postAgentArgs } = parseAgentArg(args.slice(1));
        const { force, remainingArgs: postForceArgs } = parseForce(postAgentArgs);
        if (postForceArgs.length > 0) {
          console.error(`Unknown option(s) for refactor prototype: ${postForceArgs.join(" ")}`);
          printUsage();
          process.exitCode = 1;
          return;
        }

        await runRefactorPrototype({ provider, force });
        return;
      } catch (error) {
        console.error(error instanceof Error ? error.message : String(error));
        printUsage();
        process.exitCode = 1;
        return;
      }
    }

    console.error(`Unknown refactor subcommand: ${subcommand}`);
    printUsage();
    process.exitCode = 1;
    return;
  }

  if (command === "approve") {
    if (args.length === 0) {
      console.error("Usage for approve: nvst approve <requirement|prototype> [--force]");
      printUsage();
      process.exitCode = 1;
      return;
    }

    const subcommand = args[0];
    const { force, remainingArgs: unknownArgs } = parseForce(args.slice(1));
    if (unknownArgs.length > 0) {
      console.error(`Unknown option(s) for approve ${subcommand}: ${unknownArgs.join(" ")}`);
      printUsage();
      process.exitCode = 1;
      return;
    }

    if (subcommand === "requirement") {
      await runApproveRequirement({ force });
      return;
    }

    if (subcommand === "prototype") {
      await runApprovePrototype({ force });
      return;
    }

    console.error(`Unknown approve subcommand: ${subcommand}`);
    printUsage();
    process.exitCode = 1;
    return;
  }

  if (command === "write-json") {
    await runWriteJson({ args });
    return;
  }

  console.error(`Unknown command: ${command}`);
  printUsage();
  process.exitCode = 1;
}

main().catch((error) => {
  if (error instanceof GuardrailAbortError) {
    // exitCode already set and "Aborted." already written by assertGuardrail
    return;
  }
  console.error("nvst failed:", error);
  process.exitCode = 1;
});
