#!/usr/bin/env bun

import { runDestroy } from "./commands/destroy";
import { runInit } from "./commands/init";
import { runStartIteration } from "./commands/start-iteration";

function printUsage() {
  console.log(`Usage: nvst <command> [options]

Commands:
  init               Initialize toolkit files in the current directory
  start iteration    Start a new iteration (archives previous if exists)
  destroy [--clean]  Remove files generated by nvst

Options:
  --clean            When used with destroy, also removes .agents/flow/archived
  -h, --help         Show this help message`);
}

async function main() {
  const [, , command, ...args] = process.argv;

  if (!command || command === "-h" || command === "--help" || command === "help") {
    printUsage();
    return;
  }

  if (command === "init") {
    if (args.length > 0) {
      console.error(`Unknown option(s) for init: ${args.join(" ")}`);
      printUsage();
      process.exitCode = 1;
      return;
    }
    await runInit();
    return;
  }

  if (command === "destroy") {
    const clean = args.includes("--clean");
    const unknownArgs = args.filter((arg) => arg !== "--clean");
    if (unknownArgs.length > 0) {
      console.error(`Unknown option(s) for destroy: ${unknownArgs.join(" ")}`);
      printUsage();
      process.exitCode = 1;
      return;
    }
    await runDestroy({ clean });
    return;
  }

  if (command === "start") {
    if (args[0] !== "iteration" || args.length !== 1) {
      console.error(`Usage for start: nvst start iteration`);
      printUsage();
      process.exitCode = 1;
      return;
    }
    await runStartIteration();
    return;
  }

  console.error(`Unknown command: ${command}`);
  printUsage();
  process.exitCode = 1;
}

main().catch((error) => {
  console.error("nvst failed:", error);
  process.exitCode = 1;
});
