#!/usr/bin/env bun

import { parseAgentArg } from "./agent";
import { runCreateProjectContext } from "./commands/create-project-context";
import { runDestroy } from "./commands/destroy";
import { runInit } from "./commands/init";
import { runStartIteration } from "./commands/start-iteration";

function parseMode(args: string[]): { mode: "strict" | "yolo"; remainingArgs: string[] } {
  const idx = args.indexOf("--mode");
  if (idx === -1) {
    return { mode: "strict", remainingArgs: args };
  }
  if (idx + 1 >= args.length) {
    throw new Error("Missing value for --mode. Expected: strict or yolo.");
  }

  const mode = args[idx + 1];
  if (mode !== "strict" && mode !== "yolo") {
    throw new Error(`Invalid --mode '${mode}'. Expected: strict or yolo.`);
  }

  const remainingArgs = [...args.slice(0, idx), ...args.slice(idx + 2)];
  return { mode, remainingArgs };
}

function printUsage() {
  console.log(`Usage: nvst <command> [options]

Commands:
  init               Initialize toolkit files in the current directory
  start iteration    Start a new iteration (archives previous if exists)
  create project-context --agent <provider> [--mode strict|yolo]
                     Generate/update .agents/PROJECT_CONTEXT.md via agent
  destroy [--clean]  Remove files generated by nvst

Options:
  --agent            Agent provider (claude, codex, gemini) for create
  --mode             Create mode for project-context (strict or yolo)
  --clean            When used with destroy, also removes .agents/flow/archived
  -h, --help         Show this help message`);
}

async function main() {
  const [, , command, ...args] = process.argv;

  if (!command || command === "-h" || command === "--help" || command === "help") {
    printUsage();
    return;
  }

  if (command === "init") {
    if (args.length > 0) {
      console.error(`Unknown option(s) for init: ${args.join(" ")}`);
      printUsage();
      process.exitCode = 1;
      return;
    }
    await runInit();
    return;
  }

  if (command === "destroy") {
    const clean = args.includes("--clean");
    const unknownArgs = args.filter((arg) => arg !== "--clean");
    if (unknownArgs.length > 0) {
      console.error(`Unknown option(s) for destroy: ${unknownArgs.join(" ")}`);
      printUsage();
      process.exitCode = 1;
      return;
    }
    await runDestroy({ clean });
    return;
  }

  if (command === "start") {
    if (args[0] !== "iteration" || args.length !== 1) {
      console.error(`Usage for start: nvst start iteration`);
      printUsage();
      process.exitCode = 1;
      return;
    }
    await runStartIteration();
    return;
  }

  if (command === "create") {
    if (args.length === 0 || args[0] !== "project-context") {
      console.error(
        `Usage for create: nvst create project-context --agent <provider> [--mode strict|yolo]`,
      );
      printUsage();
      process.exitCode = 1;
      return;
    }

    try {
      const { provider, remainingArgs: postAgentArgs } = parseAgentArg(args.slice(1));
      const { mode, remainingArgs: postModeArgs } = parseMode(postAgentArgs);

      if (postModeArgs.length > 0) {
        console.error(`Unknown option(s) for create project-context: ${postModeArgs.join(" ")}`);
        printUsage();
        process.exitCode = 1;
        return;
      }

      await runCreateProjectContext({ provider, mode });
      return;
    } catch (error) {
      console.error(error instanceof Error ? error.message : String(error));
      printUsage();
      process.exitCode = 1;
      return;
    }
  }

  console.error(`Unknown command: ${command}`);
  printUsage();
  process.exitCode = 1;
}

main().catch((error) => {
  console.error("nvst failed:", error);
  process.exitCode = 1;
});
